- hosts: all
  user: vagrant
  sudo: true

  tasks:
    - name: Install ruby-dev
      apt: name=ruby-dev update_cache=true

    - name: Install Bundler
      shell: gem install bundler --no-rdoc --no-ri
      args:
        chdir: /vagrant/

    - name: Install WaniKani To Anki gems
      shell: bundle install --quiet
      args:
        chdir: /vagrant/

    - name: Starting up WaniKani To Anki
      shell: rackup -D
      args:
        chdir: /vagrant/

